name: quickcash
description: "Quickcash App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 6.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^1.1.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  percent_indicator: ^4.2.2
  intl_phone_field: ^3.2.0
  country_state_city_pro: ^0.0.6
  image_picker: ^1.1.2
  syncfusion_flutter_charts: ^27.1.56
  fl_chart: ^0.69.0
  flutter_quill: ^10.8.5
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  either_dart: ^0.3.0
  bloc: ^8.1.4
  country_picker: ^2.0.26
  country_flags: ^3.0.0
  intl: ^0.19.0
  image: ^3.3.0
  razorpay_flutter: 1.3.7
  connectivity_plus: ^6.1.0
  flutter_stripe: ^11.3.0
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  web_socket_channel: ^3.0.1
  webview_flutter: ^4.10.0
  flutter_launcher_icons: ^0.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

